name: Проверка
on: [push]
jobs:
  linter_1:
    name: Линтер HW1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 hw1.py test_hw1.py
  tests_1:
    name: Тесты HW1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
        pip install numpy
    - name: Pytest
      run: pytest test_hw1.py
  linter_3:
    name: Линтер HW3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: |
        flake8 hw3.py
        cd tests_hw3 && flake8
  tests_3:
    name: Тесты HW3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
        pip install numpy
    - name: Pytest
      run: cd tests_hw3 && pytest .