name: Проверка
on: [push]
jobs:
  linter_for_hw1:
    name: Линтер для дз1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 hw1.py test_hw1.py
  tests_for_hw1:
    name: Тесты для дз1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
        pip install numpy
    - name: Pytest
      run: pytest test_hw1.py
  linter_for_hw2:
      name: Линтер для дз2
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
      - name: Flake8
        run: flake8 hw2.py test_hw2.py
  tests_for_hw2:
      name: Тесты для дз2
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest==6.2.5
          pip install numpy
      - name: Pytest
        run: pytest test_hw2.py