name: Проверка домашних заданий
on: [push]
env:
  PYTHON_VERSION: 3.11.6
jobs:
  flake:
    strategy:
      matrix:
        name: ['hw1', 'hw3']
    name: ${{ matrix.name }}. Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
      - name: Запуск Flake8
        run: flake8 ${{ matrix.name }}
  pytest:
    strategy:
      matrix:
        name: ['hw1', 'hw3']
    name: ${{ matrix.name }}. Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install pytest==6.2.5
      - name: Запуск Pytest
        run: pytest ${{ matrix.name }}
