name: Проверка
on: [push]
jobs:
  linter_hw1:
    name: Линтер hw1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 .
  tests_hw1:
    name: Тесты hw1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
        pip install numpy
    - name: Pytest
      run: |
        pytest hw1
  linter_hw2:
    name: Линтер hw3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 .
  tests_hw2:
    name: Тесты hw3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
        pip install numpy
    - name: Pytest
      run: |
         pytest hw3.py