name: Проверка
on: [push]
jobs:
  linter_hw1:
    name: Линтер hw1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 hw1
  tests_hw1:
    name: Тесты hw1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==6.2.5
    - name: Pytest
      run: pytest hw1/test_hw1.py
  linter_hw2:
    name: Линтер hw2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.1.0 flake8_isort==6.1.0 wemake-python-styleguide==0.18.0 bandit==1.7.5
    - name: Flake8
      run: flake8 hw2
  tests_hw2:
    name: Тесты hw2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.4.2
    - name: Pytest
      run: pytest hw2/test_hw2.py